### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by taishinaritomi** [taishinaritomi/kaze-style#9]
## New
- [x] global css
- [ ] document website
- [x] React Server Component
## Fix
- [x] runtime css
- [x] css Rule order
- [x] createStyle globalStyle type
- [x] remove core package dependency stylis
## New Package
- [x] create a package of build (@kaze-style/build)
- [x] create a package of themes (@kaze-style/themes)
## Plugin Library Support
- [x] vite-plugin
- [x] swc-plugin
